### ISSUE TITLE
kubernetes cluster not explicitly linked to project.

### ISSUE THREAD

**Issue by brucellino** [brucellino/terraform-digitalocean-kubernetes#10]
Seems that when making destructive changes to the k8s cluster, we break the association between the project and the cluster:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=<tag>

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: <tag>

# Specify a custom namespace in which to install AWX
namespace: awx
```

This seems to be because the cluster is removed immediately
